Repository HiZollo/Junior-HiZollo, pull requests merged in 2022-10, with the labels that each got.

#18 feature: new responses for confession command
  src/commands/Confession.ts
Labels: enhancement

#20 feature: open access to all discord activities
  src/commands/Activity.ts
Labels: enhancement

#21 chore: finalized of the new release
  package-lock.json
  package.json
  src/app.ts
  src/constant.json
  src/features/info/recentUpdate.ts
Labels: prerelease

#25 chore: fix wrong class name
  src/commands/Dmuser.ts
Labels: typo
