Repository HiZollo/Junior-HiZollo, pull requests merged in 2022-11, with the labels that each got.

#26 chore: update dependencies to latest
  .gitignore
  config.ts
  package-lock.json
  package.json
  src/classes/CommandManager.ts
  src/classes/HZNetwork.ts
  src/classes/HiddenCommand.ts
  src/classes/Music/Controller/GuildMusicController.ts
  src/classes/Source.ts
  src/commands/Help.ts
  src/features/utils/modalSystem.ts
  src/features/utils/pageSystem.ts
  src/features/utils/tempMessage.ts
  src/utils/interfaces.ts
Labels: bug, upgrade

#30 修理MD022(markdownlint)+修理codeblock
  README.md
Labels: typo

#31 修理一個點
  src/pictures/coin-disappear.png
  src/pictures/coin-hundred.png
  src/pictures/coin-stand.png
Labels: enhancement
