Repository HiZollo/Junior-HiZollo, pull requests merged in 2022-09, with the labels that each got.

#12 feature: connection 指令現在會顯示語音頻道中的人數與工作狀態
  src/commands/Connection.ts
Labels: bug, enhancement

#13 feature: buttonrole 新增修改與移除單個按鈕的方法
  src/commands/Buttonrole.ts
Labels: enhancement

#15 chore: fix wrong description in issue template "hizollo"
  .github/ISSUE_TEMPLATE/hizollo.yml
Labels: typo
