Repository HiZollo/Junior-HiZollo, pull requests merged in 2024-08, with the labels that each got.

#62 更新套件版本並修復少量漏洞
  package-lock.json
  package.json
  src/classes/CommandParser.ts
  src/commands/Calc.ts
  src/features/utils/isEmoji.ts
  src/features/utils/modalSystem.ts
  src/typings/interfaces.ts
Labels: upgrade

#63 一些雜事
  src/classes/CommandParser.ts
  src/classes/HiddenCommand.ts
  src/classes/Source.ts
  src/commands/Bug.ts
  src/commands/Buttonrole.ts
  src/commands/Server.ts
  src/commands/Sponsor.ts
  src/commands/Suggest.ts
  src/commands/Vote.ts
  src/features/json/gameString.json
  src/features/utils/isEmoji.ts
  src/hidden/Gg.ts
  src/hidden/Haha.ts
  src/hidden/Lagbot.ts
  src/hidden/Lanbot.ts
  src/hidden/Lol.ts
  src/hidden/Noisy.ts
  src/hidden/Noword.ts
  src/hidden/Omg.ts
  src/hidden/Oof.ts
  src/hidden/Pray.ts
  src/hidden/Tagged.ts
  src/hidden/Thanks.ts
  src/hidden/Useful.ts
  src/hidden/Wronghelp.ts
  src/hidden/Www.ts
  src/hidden/Yee.ts
  src/pictures/tagged_epic_1.png
  src/pictures/tagged_epic_2.png
  src/pictures/tagged_epic_3.png
Labels: bug, enhancement

#61 feature: add weighted choose command & fix
  src/commands/Calc.ts
  src/commands/Choose.ts
Labels: enhancement
