Repository HiZollo/Junior-HiZollo, pull requests merged in 2024-09, with the labels that each got.

#66 改使用應用程式表情來儲存自訂表情
  app_emoji.json
  src/classes/HZNetwork.ts
  src/classes/Music/Controller/GuildMusicController.ts
  src/commands/2048.ts
  src/commands/Bigtwo.ts
  src/commands/Bullsandcows.ts
  src/commands/Dice.ts
  src/commands/Finalcode.ts
  src/commands/Fliptrip.ts
  src/commands/Gomoku.ts
  src/commands/Lightsup.ts
  src/commands/Think.ts
  src/commands/Tictactoe.ts
  src/features/info/gameString.ts
  src/features/utils/pageSystem.ts
  src/hidden/Tagged.ts
Labels: enhancement

#67 讓部分回覆可以 tag
  src/app.ts
  src/hidden/Thanks.ts
Labels: bug, enhancement

#68 V1.4.0
  constant.json
  package-lock.json
  package.json
  src/app.ts
  src/commands/Choose.ts
  src/features/info/recentUpdate.ts
Labels: prerelease
